### ISSUE TITLE
AWS resources

### ISSUE THREAD

**Issue by sherrerq** [Sean-Bradley/Tutorials#1]
Dear,

I am interested in doing some of your monitoring courses but I am not sure if I will learn how to monitor son AWS resources like RDS or ALB. Is this taught in the Zabbix course uploaded in Udemy?

Best Regards

**Comment by Sean-Bradley** [comment]
No AWS specifics are taught by me in this Zabbix course yet. But I show to import templates from [Zabbix Share](https://share.zabbix.com/cloud/aws) here [Importing Templates](https://sbcode.net/zabbix/importing-templates/). There are AWS specific templates on Zabbix share that will help you with monitoring AWS. I also teach the Zabbix API, so you could write your own AWS monitoring middleware if you felt like it. Although the Zabbix Share resources are as best as you'll get without needing to write it yourself. If you installed your MySQL manually on an EC2, you could install the Zabbix agent, and then follow the tutorial I created for [Monitoring MySQL](https://sbcode.net/zabbix/setup_mysql_database_monitoring/)
